title: Smartsched
description: Aplikasi manajemen tugas berbasis AI yang secara otomatis menyusun prioritas tugas berdasarkan deadline, tingkat kesulitan, dan kompleksitas tugas
theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme