name: Test, Build Senpro B1-14

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build

  deploy:
    needs: test-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          SCRIPT: |
            echo "Cek folder project";
            [ ! -d "${HOME}/repos/KELOMPOK-B1-14/" ] &&
              {
                echo "Repository belum di-clone. Cloning...";
                mkdir -p ~/repos;
                cd ~/repos;
                git clone https://github.com/auroraam/KELOMPOK-B1-14;
                cd ~/repos/KELOMPOK-B1-14;
                echo "Install Package dan Build Project";
                npm install;
                npm run build;
              } ||
              {
                echo "Repository sudah ada. Building....";
                cd ~/repos/KELOMPOK-B1-14;
                git restore .;
                git pull origin main;
                echo "Install Package dan Build Project";
                npm install;
                npm run build;
              }