name: Test, Build SmartSched

on:
  push:
    branches: [main]

jobs: 
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Testing Frontend
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json 
      - run: |
          cd frontend
          npm install
          npm run build

      - name: Testing Backend
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json 
      - run: |
          cd backend
          npm install
          node server.js &  # Jalankan server di background
          SERVER_PID=$!

          # Tunggu server berjalan maksimal 10 detik
          for i in {1..10}; do
            curl -I http://localhost:3000 && break
            echo "Waiting for server..."
            sleep 2
          done

          # Matikan server setelah selesai testing
          kill $SERVER_PID