name: Test, Build SmartSched

on:
  push:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      # 🔹 Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # 🔹 Install dan Jalankan Backend
      - name: Install & Start Backend
        run: |
          cd backend
          npm install
          node server.js &  # Jalankan di background
          echo "BACKEND_PID=$!" >> $GITHUB_ENV  # Simpan PID backend

      # 🔹 Tunggu Backend Siap
      - name: Wait for Backend
        run: |
          for i in {1..10}; do
            curl -I http://localhost:3500 && break
            echo "Waiting for backend..."
            sleep 2
          done

      # 🔹 Install dan Jalankan Frontend
      - name: Install & Start Frontend
        run: |
          cd frontend
          npm install
          npm run dev &  # Jalankan di background
          echo "FRONTEND_PID=$!" >> $GITHUB_ENV  # Simpan PID frontend

      # 🔹 Tunggu Frontend Siap
      - name: Wait for Frontend
        run: |
          for i in {1..10}; do
            curl -I http://localhost:3000 && break  # Ganti dengan port yang dipakai frontend
            echo "Waiting for frontend..."
            sleep 2
          done

      # 🔹 Matikan Backend dan Frontend setelah testing
      - name: Stop Backend & Frontend
        run: |
          echo "Stopping Backend (PID: $BACKEND_PID) & Frontend (PID: $FRONTEND_PID)"
          kill $BACKEND_PID || echo "Backend already stopped"
          kill $FRONTEND_PID || echo "Frontend already stopped"