name: Test, Build Senpro B1-14

on:
  push:
    branches: [main]

jobs: 
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json  # Tidak ada folder khusus, langsung gunakan package-lock.json utama

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Jalankan build, baik untuk Next.js atau proyek lain

      - name: Start Server for Testing
        run: |
          node server.js &  # Jalankan server di background
          SERVER_PID=$!

          # Tunggu server berjalan maksimal 10 detik
          for i in {1..10}; do
            curl -I http://localhost:3000 && break
            echo "Waiting for server..."
            sleep 2
          done

          # Matikan server setelah selesai testing
          kill $SERVER_PID